name: hotlist

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 * * * *'

jobs:
  weibo:
    runs-on: ubuntu-latest
    services:
      chrome:
        image: browserless/chrome
        ports:
          - 3000:3000
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install
      - run: node weibo.js > weibo.json
      - run: jq -e 'length > 0' weibo.json
      - id: date
        run: echo "::set-output name=dt::$(date +%Y%m%d-%H%M%S)"
      - uses: softprops/action-gh-release@v1
        with:
          tag_name: hotlist-${{ steps.date.outputs.dt }}
          files: |
            weibo.json
            weibo.png
