name: hotlist

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 * * * *'

jobs:
  crawl:
    runs-on: ubuntu-latest
    services:
      chrome:
        image: browserless/chrome
        ports:
          - 3000:3000
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: |
          wget https://github.com/mgdm/htmlq/releases/download/v0.4.0/htmlq-x86_64-linux.tar.gz
          tar xzf htmlq-x86_64-linux.tar.gz
          sudo mv htmlq /usr/local/bin/
      - run: npm install
      - run: |
          bash baidu.sh > baidu.json
          bash sogou.sh > sogou.json
          bash toutiao.sh > toutiao.json
          bash zhihu.sh > zhihu.json
          node bilibili.js > bilibili.json
          node weibo.js > weibo.json
      - id: date
        run: echo "::set-output name=dt::$(TZ=UTC date +%Y%m%d-%H%M%S)"
      - uses: softprops/action-gh-release@v1
        with:
          tag_name: hotlist-${{ steps.date.outputs.dt }}
          files: |
            baidu.json
            sogou.json
            toutiao.json
            zhihu.json
            bilibili.json
            bilibili.png
            weibo.json
            weibo.png
